project:
  type: website
  output-dir: docs

website:
  title: "nbpages"
  navbar:
    background: light
    right:
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - example.ipynb

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
