project:
  type: website
  output-dir: docs

website:
  title: "nbpages"
  navbar:
    background: light
    right:
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - posts/example.ipynb
      - posts/toc.ipynb
      - posts/tocdepth.qmd

format:
  html:
    toc: true
    toc-depth: 5
    theme: cosmo
    css: styles.css

